### ISSUE TITLE
Compatibility with Python 3.7 with no GPU

### ISSUE THREAD

**Issue by vaibhav90** [vonfeng/DeepMove#1]
Hello, Thank you for this very interesting work! If anyone wants to run this on Python 3.7 with no cuda enabled, you need to do the following changes. 

1. `import cPickle as pickle -> import pickle`

2. Avoid error while reading ASCII with pickle  

`data = pickle.load(open(self.data_path + self.data_name + '.pk', 'rb'))` - > 

```
with open(self.data_path + self.data_name + '.pk', 'rb') as f:
            u = pickle._Unpickler(f)
            u.encoding = 'latin1'
            data = u.load()
```

3. There is a race condition occuraing while creating directories

`os.mkdir(SAVE_PATH + tmp_path)` - > `os.makedirs(SAVE_PATH + tmp_path, exist_ok=True)`

**Comment by vonfeng** [comment]
Thank you for your valuable supplement~
