### ISSUE TITLE
An indent bug in train.py

### ISSUE THREAD

**Issue by JerryLife** [vonfeng/DeepMove#2]
https://github.com/vonfeng/DeepMove/blob/0acff5d88d70d31a4fcf580648e0056e103dc6cf/codes/train.py#L143-L154
What does _i_ in _data_train[u][i] = trace_ refer to? Might be some missing indentations?

**Comment by vonfeng** [comment]
`i` is just for compatibility. Actually, it can be any number. Maybe I should replace it by `0` to avoid misunderstanding.
